# Generated by Django 3.2.3 on 2021-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
