# Generated by Django 3.2.3 on 2021-05-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=140),
        ),
    ]
